#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# translate_all_to_english:
#   path: /translate/all
#   controller: App\Controller\TranslationController::translateAllToEnglish
