# config/services.yaml

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Service\QrCodeGeneratorService: 
        autowire: true
        autoconfigure: true
    App\Service\StripeController: ~
      
      